[book]
language = "uk"
multilingual = false
src = "docs"

# Замініть авторство проєкта на своє
authors = ["Ivan \"ukrustacean\" Dereviankin"]

# Змініть назву проєкта на свою
title = "пу-пу-пу3"

[preprocessor.plantuml]
plantuml-cmd = "http://www.plantuml.com/plantuml"
use-data-uris = true
